name: TypeScript PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ts

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Restore npm packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Eslint
        run: npm run eslint
      
      - name: Pack
        run: npm run pack
